<a href="https://colab.research.google.com/github/deansadang/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np 
from numpy.linalg import eig 

**Problem #1**

In [17]:
S1 = np.array([[1, 1, 1],[1, 0, 4], [0, 0, 5]])
S2 = np.array([[89], [89], [95]])

T = np.linalg.inv(S1).dot(S2)
print(T)

[[13.]
 [57.]
 [19.]]


**Problem #2**

In [18]:
A = np.array([[3,-1,1], [9,-3,3], [-12,4,-4]])
print("Matrix A:\n", A)

#The matrix is singular, we cannot somehow inverse it but we can use pinv to see the output and the results.

inv_A = np.linalg.pinv(A)
print("\nInverse of Matrix A:\n", inv_A)

B = np.array([[5],[10],[-20]])
print("\nMatrix A:\n", A)

X = np.dot(inv_A, B)
print("\nDot:\n", X)

C = np.dot(A, X)
print("\nChecking:\n", C)

Matrix A:
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Inverse of Matrix A:
 [[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]]

Matrix A:
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Dot:
 [[ 1.20629371]
 [-0.4020979 ]
 [ 0.4020979 ]]

Checking:
 [[  4.42307692]
 [ 13.26923077]
 [-17.69230769]]


**Problem #3**

In [14]:
z = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(z)
b,c =np.linalg.eig(z)
print("The eigenvalue/s is/are:" ,b)
print("The eigenvectors are",c)
x = c.round()
print(x)


[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s is/are: [-1.  3.  2.]
The eigenvectors are [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
