<a href="https://colab.research.google.com/github/deansadang/Linear-Algebra-58020/blob/main/Inverse_and_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
A = np.array([[1,2],[4,7]])
invA = (np.linalg.inv(A))
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [3]:
C = np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


**Program that applies the inverse of a 3x3 Matrix**

In [10]:
B = np.array([[8,9,5],[3,4,2],[4,5,3]])
invB = np.linalg.inv(B)
print(invB)



[[ 1.  -1.  -1. ]
 [-0.5  2.  -0.5]
 [-0.5 -2.   2.5]]


In [11]:
C = np.dot(B,invB)
print(C)

[[ 1.0000000e+00 -4.4408921e-16  4.4408921e-16]
 [ 0.0000000e+00  1.0000000e+00  8.8817842e-16]
 [ 0.0000000e+00 -4.4408921e-16  1.0000000e+00]]


**Transpose of the Matrix**

In [13]:
D = np.transpose(B)
print(D)

[[8 3 4]
 [9 4 5]
 [5 2 3]]


**Inverse of a 4x4 Matrix**

In [15]:
E = np.array([[3,4,6,5],[9,8,3,2],[5,8,6,4],[2,5,4,3]])
print(E)

[[3 4 6 5]
 [9 8 3 2]
 [5 8 6 4]
 [2 5 4 3]]


In [16]:
F= np.linalg.inv(E)
print(F)

[[ 0.14545455  0.10909091  0.09090909 -0.43636364]
 [-0.23636364  0.07272727 -0.27272727  0.70909091]
 [-0.03636364 -0.52727273  1.72727273 -1.89090909]
 [ 0.34545455  0.50909091 -1.90909091  1.96363636]]


**Transpose of the 4x4 Matrix**

In [18]:
G= np.transpose(E)
print(G)

[[3 9 5 2]
 [4 8 8 5]
 [6 3 6 4]
 [5 2 4 3]]
