<a href="https://colab.research.google.com/github/deansadang/Linear-Algebra-58020/blob/main/Midterm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

**Question #1 Create a Python code that displays a square matrix whose length is 5**

In [2]:
A = np.eye(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Question #2 Create a Python code that displays a square matrix whose elements below the principal diagonal are zero**

In [3]:
B = np.eye(4)
print(B)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Question #3 Create a Python code that displays a square matrix which is symmetrical**


In [9]:
B2 = np.array([[1,2,6],[2,8,4],[6,4,5]])
print(B2)

[[1 2 6]
 [2 8 4]
 [6 4 5]]


**Question #4 What is the inverse of matrix C? Show your solution by python coding.**

In [5]:
V = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(V)
f = np.linalg.inv(V)
print(f)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


**Question #5 What is the determinant of the given matrix in Question 4? Show your solution by python coding.**

In [6]:
V = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(V)
print(np.linalg.det(V))
print(round(np.linalg.det(V)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


**Question #6 Find the roots of the linear equations by showing its python codes.**

In [11]:
D = np.array([[5,4,1,3.4],[10,9,4,8.8],[10,13,15,19.2]]) 
print(D)

sqrtD = np.sqrt(D) 
print(" ")
print("Roots")
print(" ")
print(sqrtD)

[[ 5.   4.   1.   3.4]
 [10.   9.   4.   8.8]
 [10.  13.  15.  19.2]]
 
Roots
 
[[2.23606798 2.         1.         1.84390889]
 [3.16227766 3.         2.         2.96647939]
 [3.16227766 3.60555128 3.87298335 4.38178046]]
