<a href="https://colab.research.google.com/github/deansadang/Linear-Algebra-58020/blob/main/Practical_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**

In [45]:
import numpy as np

In [59]:

W = np.array([[1,-3,0],[2,-2,0],[3,1,0]])

X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])

Y = np.array ([[1,2,0],[0,-1,2],[0,0,0]])

Z = np.array ([[0,1],[2,3]])


In [61]:
#A
output = np.dot(W,Y)
print(output)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [62]:
#B
output = np.add(Z,Z)
print(output)

[[0 2]
 [4 6]]


In [63]:
#C
output = np.dot(3,X)
print(output)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


**Problem 2**

In [64]:
#A product is not defined
ans1 = np.cross(Y,W)

ans2 = 2*ans1
print(ans2)

#A is false

[[  0   0 -10]
 [  8   8   4]
 [  0   0   0]]


In [66]:
#B
b1 = np.dot(W,Y)
b2 = np.subtract(b1,X)
print(b2)

#B is false

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [68]:
#C
c1=np.dot(Y,W)
c2 =2*Z

c1 = ([[5,-7],[4,4]])
c3 = np.subtract(c1,c2)
print(c3)

#C is true

[[ 5 -9]
 [ 0 -2]]
