<a href="https://colab.research.google.com/github/deansadang/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Qeustion #1

In [2]:
import numpy as np 

In [8]:
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question #2

In [9]:
answer = 2*C

print(answer)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question #3

In [12]:
A =([2,7,4])
B = ([3,9,8])

output = np.cross(A,B)
print(output)

[20 -4 -3]
